name: chicago
version: 0.1.0-dev
repository: https://github.com/tvolkert/chicago

description:
  The Chicago widget set is an alternate design language for Flutter designed
  for desktop (keyboard and mouse) form factors. It is based on Apache Pivot.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.3.0-12.1.pre"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
