name: chicago
description: The Chicago widget set for Flutter
version: 0.0.1-dev
repository: https://github.com/tvolkert/chicago

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
